# Dictionary containing translations for English, Turkish, and German
TRANSLATIONS = {
    "en": {
        # Titles
        "page_title_setup": "Docker Backup Guard - Setup",
        "header_setup": "🛠️ Initial Setup Wizard",
        "page_title_dashboard": "Docker Backup Guard",
        "header_dashboard": "📦 Docker Backup Guard Dashboard",
        
        # Setup Wizard
        "warning_env_missing": "⚠️ Configuration file (`.env`) not found. Please configure the settings below before using the system.",
        "subheader_portainer": "🚀 Portainer Integration",
        "info_portainer": "Portainer API access is required to manage containers.",
        "label_portainer_url": "Portainer URL",
        "label_portainer_token": "Portainer Access Token",
        "help_portainer_token": "API Token obtained from Portainer",
        "btn_test_connection": "🧪 Test Connection",
        "btn_test_gotify": "🔔 Test Gotify",
        "status_test_success": "✅ Connection Successful!",
        "status_test_failed": "❌ Connection Failed. Check URL and Token.",
        
        "subheader_gotify": "🔔 Notifications (Gotify)",
        "info_gotify": "Used to report backup statuses.",
        "label_gotify_url": "Gotify URL",
        "label_gotify_token": "Gotify App Token",
        
        "subheader_security": "🔒 Security & Backup",
        "label_backup_pass": "Backup Encryption Password",
        "help_backup_pass": "Key used for AES-256 encryption.",
        "label_retention": "Retention Period (Days)",
        "help_retention": "Duration to keep old backups.",
        "label_timezone": "Timezone",
        "label_healthcheck": "Healthcheck URL (Optional)",
        
        "subheader_rclone": "☁️ Rclone Settings",
        "label_rclone_path": "Rclone Config Path",
        "help_rclone_path": "Path to rclone.conf mounted inside the container.",
        "label_rclone_remote": "Rclone Remote Name",
        "help_rclone_remote": "Name of the remote configured in rclone.conf (e.g., 'gdrive').",
        "label_rclone_dest": "Cloud Destination Path",
        "help_rclone_dest": "Directory on the cloud where backups will be stored (e.g., 'ServerBackups/Rpi').",
        "label_rclone_content": "Rclone Configuration Content (rclone.conf)",
        "help_rclone_content_msg": "Paste your local rclone.conf content here. Need help generating it?",
        "help_rclone_content_hint": "Run `rclone config` on your local machine, then copy the file content.",
        "warning_rclone_isdir": "⚠️ Warning: The path `{path}` is a directory (likely due to a Docker volume mount). Saving configuration to `{new_path}` instead.",
        
        "btn_save": "💾 Save Settings & Start",
        "error_missing_fields": "⛔ Error: Portainer URL, Token, and Backup Password are required!",
        "success_setup": "✅ Setup completed successfully! Restarting application...",
        
        # Dashboard
        "menu_title": "Menu",
        "system_online": "System Online",
        "subheader_candidates": "📋 Containers to Backup",
        "warning_no_candidates": "⚠️ No containers found with `backup.enable=true` label.",
        "label_status": "Status",
        "label_image": "Image",
        "btn_backup": "🚀 Backup: {name}",
        "btn_full_backup": "🚀 Start Full Backup",
        "status_backing_up": "Backing up: {name}...",
        "status_full_backup_start": "Starting Full Backup for all containers...",
        "status_scanning": "🔍 Scanning Volume and Mount points...",
        "error_no_pass": "ERROR: Backup password not found!",
        "status_failed": "Backup Failed ❌",
        "status_success_encrypt": "✅ Backup and Encryption completed.",
        "status_waiting_cloud": "☁️ Waiting for cloud sync... (Rclone)",
        "status_complete": "Backup Completed Successfully! 🎉",
        "status_error_process": "❌ Error occurred during backup.",
        "status_error_label": "Backup Error ⛔",
        
        # Notifications
        "notif_success_title": "Backup Successful",
        "notif_success_msg": "Container {name} successfully backed up.",
        "notif_full_success_title": "Full Backup Successful",
        "notif_full_success_msg": "All containers backed up and synced to cloud.",
        "notif_error_title": "Backup Error",
        "notif_error_msg": "Error backing up {name}!",
        "notif_full_error_title": "Full Backup Error",
        "notif_full_error_msg": "An error occurred during full backup.",
        
        # Settings View
        "checkbox_show_settings": "Show Settings (Masked)",
        "lang_select_label": "Select Language / Dil Seçimi / Sprache wählen",
        
        # Tabs & New UI
        "tab_dashboard": "Dashboard",
        "tab_settings": "Settings",
        "tab_actions": "Action Center",
        "tab_logs": "Logs",
        "header_overview": "System Overview",
        "metric_last_success": "Last Successful Backup",
        "metric_last_size": "Last Backup Size",
        "metric_protected": "Protected Containers",
        "header_config": "Configuration",
        "header_automation": "🤖 Automation / Scheduler",
        "label_schedule_enable": "Enable Automatic Backup",
        "label_schedule_time": "Daily Backup Time",
        "help_schedule_time": "Time to run backup every day (24h format).",
        "label_heartbeat_enable": "Enable Heartbeat (Uptime Monitor)",
        "label_heartbeat_url": "Heartbeat URL (Optional)",
        "help_heartbeat_url": "URL for Uptime Kuma/Healthchecks.io to signal 'System is Alive'.",
        "label_heartbeat_interval": "Heartbeat Interval (Minutes)",
        "help_heartbeat_interval": "How often to send a ping. Set to 0 to disable.",
        "toggle_edit": "Unlock / Edit Settings",
        "toggle_show_backup_password": "Show Backup Password",
        "help_show_backup_password": "Reveal the current backup password in the settings form.",
        "header_logs": "System Logs",
        "btn_refresh_logs": "Refresh Logs",
        "btn_clear_logs": "🗑️ Clear Logs",
        "status_logs_cleared": "✅ Logs cleared successfully.",
        "btn_save_changes": "Save Changes",
        "status_settings_saved": "✅ Settings saved! Reloading...",
        "error_backup_pass_required": "⛔ Backup password cannot be empty.",
        
        # Portainer Backup
        "subheader_portainer_backup": "Portainer Configuration Backup",
        "btn_backup_portainer": "📦 Backup Portainer Config Only",
        "status_backup_portainer_start": "Backing up Portainer Configuration...",
        "status_backup_portainer_success": "✅ Portainer Configuration Backup Successful!",
        "status_backup_portainer_failed": "❌ Portainer Backup Failed!",

        # Progress Messages
        "progress_processing_group": "Processing Group: {group} ({count} containers)",
        "progress_stopping": "⏹️ Stopping {group}...",
        "progress_snapshot": "📸 Snapshotting: {path}",
        "progress_error_group": "❌ Error in group {group}: {error}",
        "progress_restarting": "▶️ Restarting {group}...",
        "progress_password_error": "❌ Error: BACKUP_PASSWORD not set.",
        "progress_no_containers": "⚠️ No containers found.",
        "progress_backup_portainer": "📦 Backing up Portainer Configuration...",
        "progress_no_data": "❌ No data found to backup.",
        "progress_compressing": "🗜️ Compressing archive (this may take a while)...",
        "progress_compression_failed": "❌ Compression Failed: {error}",
        "progress_uploading": "☁️ Uploading to Cloud...",
        "progress_upload_success": "✅ Cloud Sync Successful. Cleaning up local archive.",
        "progress_upload_failed": "⚠️ Cloud Sync Failed.",

        # Login
        "label_username": "Username",
        "label_password": "Password",
        "btn_login": "Login",
        "error_login_failed": "❌ Invalid username or password",
        "btn_logout": "Logout",
        "header_login": "🔐 Admin Login",
        "label_web_ui_username": "Web UI Username",
        "label_web_ui_password": "Web UI Password",
        "help_web_ui_creds": "Credentials to access this dashboard.",
        
        # Rclone Editor
        "subheader_rclone_editor": "📝 Rclone Config Editor",
        "btn_save_rclone": "💾 Save Rclone Config",
        "status_rclone_saved": "✅ Rclone config saved successfully!",
        "error_rclone_save": "❌ Error saving rclone config: {error}",
        "warning_ro_mount": "⚠️ Warning: File is Read-Only. Please remove ':ro' from docker-compose.yml",
        
        # UI Strings
        "unknown_permission_denied": "Unknown (Permission Denied)",
        "info_rclone_not_found": "rclone.conf not found. You can create it here.",
        "status_test_running": "Testing...",
        "warning_portainer_required": "Portainer URL & Token required.",
        "warning_gotify_required": "Gotify URL & Token required."
    },
    
    "tr": {
        # Titles
        "page_title_setup": "Docker Backup Guard - Kurulum",
        "header_setup": "🛠️ İlk Kurulum Sihirbazı",
        "page_title_dashboard": "Docker Backup Guard",
        "header_dashboard": "📦 Docker Backup Guard Paneli",
        
        # Setup Wizard
        "warning_env_missing": "⚠️ Konfigürasyon dosyası (`.env`) bulunamadı. Lütfen sistemi kullanmaya başlamadan önce aşağıdaki ayarları yapılandırın.",
        "subheader_portainer": "🚀 Portainer Entegrasyonu",
        "info_portainer": "Konteynerleri yönetmek için Portainer API erişimi gereklidir.",
        "label_portainer_url": "Portainer URL",
        "label_portainer_token": "Portainer Erişim Tokeni",
        "help_portainer_token": "Portainer'dan alacağınız API Token",
        "btn_test_connection": "🧪 Bağlantıyı Test Et",
        "btn_test_gotify": "🔔 Gotify'ı Test Et",
        "status_test_success": "✅ Bağlantı Başarılı!",
        "status_test_failed": "❌ Bağlantı Başarısız. URL ve Token'i kontrol edin.",
        
        "subheader_gotify": "🔔 Bildirimler (Gotify)",
        "info_gotify": "Yedekleme durumlarını bildirmek için kullanılır.",
        "label_gotify_url": "Gotify URL",
        "label_gotify_token": "Gotify Uygulama Tokeni",
        
        "subheader_security": "🔒 Güvenlik ve Yedekleme",
        "label_backup_pass": "Yedek Şifreleme Parolası",
        "help_backup_pass": "AES-256 şifreleme için kullanılacak anahtar.",
        "label_retention": "Saklama Süresi (Gün)",
        "help_retention": "Eski yedeklerin silinme süresi.",
        "label_timezone": "Zaman Dilimi",
        "label_healthcheck": "Healthcheck URL (Opsiyonel)",
        
        "subheader_rclone": "☁️ Rclone Ayarları",
        "label_rclone_path": "Rclone Konfigürasyon Yolu",
        "help_rclone_path": "Konteyner içine mount edilen rclone.conf dosyasının yolu.",
        "label_rclone_remote": "Rclone Remote Adı",
        "help_rclone_remote": "rclone.conf içinde tanımlanan uzak sunucu adı (örn: 'gdrive').",
        "label_rclone_dest": "Bulut Hedef Klasörü",
        "help_rclone_dest": "Yedeklerin bulutta saklanacağı klasör (örn: 'SunucuYedekleri/Rpi').",
        "label_rclone_content": "Rclone Konfigürasyon İçeriği (rclone.conf)",
        "help_rclone_content_msg": "Yerel rclone.conf içeriğinizi buraya yapıştırın. Oluşturmak için yardıma mı ihtiyacınız var?",
        "help_rclone_content_hint": "Yerel makinenizde `rclone config` komutunu çalıştırın, ardından dosya içeriğini kopyalayın.",
        "warning_rclone_isdir": "⚠️ Uyarı: `{path}` yolu bir dizin (muhtemelen Docker volume mount nedeniyle). Konfigürasyon bunun yerine `{new_path}` konumuna kaydediliyor.",
        
        "btn_save": "💾 Ayarları Kaydet ve Başlat",
        "error_missing_fields": "⛔ Hata: Portainer URL, Token ve Yedekleme Şifresi zorunludur!",
        "success_setup": "✅ Kurulum başarıyla tamamlandı! Uygulama yeniden başlatılıyor...",
        
        # Dashboard
        "menu_title": "Menü",
        "system_online": "Sistem Çevrimiçi",
        "subheader_candidates": "📋 Yedeklenecek Konteynerler",
        "warning_no_candidates": "⚠️ `backup.enable=true` etiketine sahip konteyner bulunamadı.",
        "label_status": "Durum",
        "label_image": "İmaj",
        "btn_backup": "🚀 Yedekle: {name}",
        "btn_full_backup": "🚀 Tam Yedeklemeyi Başlat",
        "status_backing_up": "Yedekleniyor: {name}...",
        "status_full_backup_start": "Tüm konteynerler için Tam Yedekleme başlatılıyor...",
        "status_scanning": "🔍 Volume ve Mount noktaları taranıyor...",
        "error_no_pass": "HATA: Yedekleme parolası bulunamadı!",
        "status_failed": "Yedekleme Başarısız ❌",
        "status_success_encrypt": "✅ Yedekleme ve Şifreleme tamamlandı.",
        "status_waiting_cloud": "☁️ Bulut senkronizasyonu bekleniyor... (Rclone)",
        "status_complete": "Yedekleme Başarıyla Tamamlandı! 🎉",
        "status_error_process": "❌ Yedekleme sırasında hata oluştu.",
        "status_error_label": "Yedekleme Hatası ⛔",
        
        # Notifications
        "notif_success_title": "Yedekleme Başarılı",
        "notif_success_msg": "{name} konteyneri başarıyla yedeklendi.",
        "notif_full_success_title": "Tam Yedekleme Başarılı",
        "notif_full_success_msg": "Tüm konteynerler yedeklendi ve buluta senkronize edildi.",
        "notif_error_title": "Yedekleme Hatası",
        "notif_error_msg": "{name} yedeklenirken hata oluştu!",
        "notif_full_error_title": "Tam Yedekleme Hatası",
        "notif_full_error_msg": "Tam yedekleme sırasında bir hata oluştu.",
        
        # Settings View
        "checkbox_show_settings": "Ayarları Göster (Maskelenmiş)",
        "lang_select_label": "Dil Seçimi / Select Language / Sprache wählen",
        
        # Tabs & New UI
        "tab_dashboard": "Kontrol Paneli",
        "tab_settings": "Ayarlar",
        "tab_actions": "İşlem Merkezi",
        "tab_logs": "Log Kayıtları",
        "header_overview": "Sisteme Genel Bakış",
        "metric_last_success": "Son Başarılı Yedek",
        "metric_last_size": "Son Yedek Boyutu",
        "metric_protected": "Korunan Konteynerler",
        "header_config": "Konfigürasyon",
        "header_automation": "🤖 Otomasyon / Zamanlayıcı",
        "label_schedule_enable": "Otomatik Yedeklemeyi Etkinleştir",
        "label_schedule_time": "Günlük Yedekleme Saati",
        "help_schedule_time": "Yedeklemenin her gün çalışacağı saat (24s formatı).",
        "label_heartbeat_enable": "Heartbeat (Uptime İzleme) Etkinleştir",
        "label_heartbeat_url": "Heartbeat URL (Opsiyonel)",
        "help_heartbeat_url": "Sistemin 'Hayattayım' sinyali göndereceği URL (Uptime Kuma vb.).",
        "label_heartbeat_interval": "Heartbeat Aralığı (Dakika)",
        "help_heartbeat_interval": "Sinyal gönderme sıklığı. Devre dışı bırakmak için 0 yapın.",
        "toggle_edit": "Kilidi Aç / Ayarları Düzenle",
        "toggle_show_backup_password": "Yedekleme Parolasını Göster",
        "help_show_backup_password": "Ayarlar formundaki mevcut yedekleme parolasını görünür yapar.",
        "header_logs": "Sistem Logları",
        "btn_refresh_logs": "Logları Yenile",
        "btn_clear_logs": "🗑️ Logları Temizle",
        "status_logs_cleared": "✅ Loglar başarıyla temizlendi.",
        "btn_save_changes": "Değişiklikleri Kaydet",
        "status_settings_saved": "✅ Ayarlar kaydedildi! Yeniden yükleniyor...",
        "error_backup_pass_required": "⛔ Yedekleme parolası boş bırakılamaz.",
        
        # Portainer Backup
        "subheader_portainer_backup": "Portainer Konfigürasyon Yedekleme",
        "btn_backup_portainer": "📦 Sadece Portainer Konfigürasyonunu Yedekle",
        "status_backup_portainer_start": "Portainer Konfigürasyonu Yedekleniyor...",
        "status_backup_portainer_success": "✅ Portainer Konfigürasyonu Başarıyla Yedeklendi!",
        "status_backup_portainer_failed": "❌ Portainer Yedeklemesi Başarısız!",

        # Progress Messages
        "progress_processing_group": "Grup İşleniyor: {group} ({count} konteyner)",
        "progress_stopping": "⏹️ Durduruluyor: {group}...",
        "progress_snapshot": "📸 Anlık Görüntü Alınıyor: {path}",
        "progress_error_group": "❌ Grup hatası {group}: {error}",
        "progress_restarting": "▶️ Yeniden Başlatılıyor: {group}...",
        "progress_password_error": "❌ Hata: BACKUP_PASSWORD ayarlanmamış.",
        "progress_no_containers": "⚠️ Yedeklenecek konteyner bulunamadı.",
        "progress_backup_portainer": "📦 Portainer Konfigürasyonu Yedekleniyor...",
        "progress_no_data": "❌ Yedeklenecek veri bulunamadı.",
        "progress_compressing": "🗜️ Arşiv sıkıştırılıyor (bu işlem biraz sürebilir)...",
        "progress_compression_failed": "❌ Sıkıştırma Başarısız: {error}",
        "progress_uploading": "☁️ Buluta Yükleniyor...",
        "progress_upload_success": "✅ Bulut Senkronizasyonu Başarılı. Yerel arşiv temizleniyor.",
        "progress_upload_failed": "⚠️ Bulut Senkronizasyonu Başarısız.",

        # Login
        "label_username": "Kullanıcı Adı",
        "label_password": "Şifre",
        "btn_login": "Giriş Yap",
        "error_login_failed": "❌ Geçersiz kullanıcı adı veya şifre",
        "btn_logout": "Çıkış Yap",
        "header_login": "🔐 Yönetici Girişi",
        "label_web_ui_username": "Web Arayüz Kullanıcı Adı",
        "label_web_ui_password": "Web Arayüz Şifresi",
        "help_web_ui_creds": "Bu panele erişim için kullanılacak kimlik bilgileri.",

        # Rclone Editor
        "subheader_rclone_editor": "📝 Rclone Konfigürasyon Editörü",
        "btn_save_rclone": "💾 Rclone Ayarlarını Kaydet",
        "status_rclone_saved": "✅ Rclone ayarları başarıyla kaydedildi!",
        "error_rclone_save": "❌ Rclone ayarları kaydedilirken hata: {error}",
        "warning_ro_mount": "⚠️ Uyarı: Dosya Salt Okunur. Lütfen docker-compose.yml dosyasından ':ro' ibaresini kaldırın.",
        
        # UI Strings
        "unknown_permission_denied": "Bilinmiyor (Erişim Reddedildi)",
        "info_rclone_not_found": "rclone.conf bulunamadı. Buradan oluşturabilirsiniz.",
        "status_test_running": "Test ediliyor...",
        "warning_portainer_required": "Portainer URL ve Token gerekli.",
        "warning_gotify_required": "Gotify URL ve Token gerekli."
    },

    "de": {
        # Titles
        "page_title_setup": "Docker Backup Guard - Einrichtung",
        "header_setup": "🛠️ Ersteinrichtungs-Assistent",
        "page_title_dashboard": "Docker Backup Guard",
        "header_dashboard": "📦 Docker Backup Guard Dashboard",
        
        # Setup Wizard
        "warning_env_missing": "⚠️ Konfigurationsdatei (`.env`) nicht gefunden. Bitte konfigurieren Sie die Einstellungen unten, bevor Sie das System verwenden.",
        "subheader_portainer": "🚀 Portainer Integration",
        "info_portainer": "Für die Verwaltung der Container ist Zugriff auf die Portainer-API erforderlich.",
        "label_portainer_url": "Portainer URL",
        "label_portainer_token": "Portainer Zugriffs-Token",
        "help_portainer_token": "API-Token von Portainer",
        "btn_test_connection": "🧪 Verbindung testen",
        "btn_test_gotify": "🔔 Gotify testen",
        "status_test_success": "✅ Verbindung erfolgreich!",
        "status_test_failed": "❌ Verbindung fehlgeschlagen. Überprüfen Sie URL und Token.",
        
        "subheader_gotify": "🔔 Benachrichtigungen (Gotify)",
        "info_gotify": "Wird verwendet, um den Sicherungsstatus zu melden.",
        "label_gotify_url": "Gotify URL",
        "label_gotify_token": "Gotify App Token",
        
        "subheader_security": "🔒 Sicherheit & Backup",
        "label_backup_pass": "Backup-Verschlüsselungspasswort",
        "help_backup_pass": "Schlüssel für AES-256-Verschlüsselung.",
        "label_retention": "Aufbewahrungsdauer (Tage)",
        "help_retention": "Dauer, für die alte Backups aufbewahrt werden.",
        "label_timezone": "Zeitzone",
        "label_healthcheck": "Healthcheck URL (Optional)",
        
        "subheader_rclone": "☁️ Rclone Einstellungen",
        "label_rclone_path": "Rclone Konfigurationspfad",
        "help_rclone_path": "Pfad zur rclone.conf, die im Container eingehängt ist.",
        "label_rclone_remote": "Rclone Remote Name",
        "help_rclone_remote": "Name des in rclone.conf konfigurierten Remote (z.B. 'gdrive').",
        "label_rclone_dest": "Cloud-Zielpfad",
        "help_rclone_dest": "Verzeichnis in der Cloud, in dem Backups gespeichert werden (z. B. 'ServerBackups/Rpi').",
        "label_rclone_content": "Rclone Konfigurationsinhalt (rclone.conf)",
        "help_rclone_content_msg": "Fügen Sie hier Ihren lokalen rclone.conf-Inhalt ein. Benötigen Sie Hilfe bei der Erstellung?",
        "help_rclone_content_hint": "Führen Sie `rclone config` auf Ihrem lokalen Computer aus und kopieren Sie dann den Dateiinhalt.",
        "warning_rclone_isdir": "⚠️ Warnung: Der Pfad `{path}` ist ein Verzeichnis (wahrscheinlich aufgrund eines Docker-Volume-Mounts). Konfiguration wird stattdessen in `{new_path}` gespeichert.",
        
        "btn_save": "💾 Einstellungen speichern & starten",
        "error_missing_fields": "⛔ Fehler: Portainer URL, Token und Backup-Passwort sind erforderlich!",
        "success_setup": "✅ Einrichtung erfolgreich abgeschlossen! Anwendung wird neu gestartet...",
        
        # Dashboard
        "menu_title": "Menü",
        "system_online": "System Online",
        "subheader_candidates": "📋 Zu sichernde Container",
        "warning_no_candidates": "⚠️ Keine Container mit dem Label `backup.enable=true` gefunden.",
        "label_status": "Status",
        "label_image": "Image",
        "btn_backup": "🚀 Sichern: {name}",
        "btn_full_backup": "🚀 Vollständiges Backup starten",
        "status_backing_up": "Sicherung läuft: {name}...",
        "status_full_backup_start": "Starte vollständiges Backup für alle Container...",
        "status_scanning": "🔍 Scanne Volume- und Mount-Punkte...",
        "error_no_pass": "FEHLER: Backup-Passwort nicht gefunden!",
        "status_failed": "Sicherung fehlgeschlagen ❌",
        "status_success_encrypt": "✅ Sicherung und Verschlüsselung abgeschlossen.",
        "status_waiting_cloud": "☁️ Warte auf Cloud-Sync... (Rclone)",
        "status_complete": "Sicherung erfolgreich abgeschlossen! 🎉",
        "status_error_process": "❌ Fehler während der Sicherung.",
        "status_error_label": "Sicherungsfehler ⛔",
        
        # Notifications
        "notif_success_title": "Sicherung erfolgreich",
        "notif_success_msg": "Container {name} erfolgreich gesichert.",
        "notif_full_success_title": "Vollständiges Backup erfolgreich",
        "notif_full_success_msg": "Alle Container gesichert und mit der Cloud synchronisiert.",
        "notif_error_title": "Sicherungsfehler",
        "notif_error_msg": "Fehler beim Sichern von {name}!",
        "notif_full_error_title": "Sicherungsfehler",
        "notif_full_error_msg": "Ein Fehler ist während des vollständigen Backups aufgetreten.",
        
        # Settings View
        "checkbox_show_settings": "Einstellungen anzeigen (Maskiert)",
        "lang_select_label": "Sprache wählen / Select Language / Dil Seçimi",
        
        # Tabs & New UI
        "tab_dashboard": "Dashboard",
        "tab_settings": "Einstellungen",
        "tab_actions": "Aktionszentrum",
        "tab_logs": "Protokolle",
        "header_overview": "Systemübersicht",
        "metric_last_success": "Letzte erfolgreiche Sicherung",
        "metric_last_size": "Letzte Sicherungsgröße",
        "metric_protected": "Geschützte Container",
        "header_config": "Konfiguration",
        "header_automation": "🤖 Automatisierung / Zeitplaner",
        "label_schedule_enable": "Automatische Sicherung aktivieren",
        "label_schedule_time": "Tägliche Backup-Zeit",
        "help_schedule_time": "Zeitpunkt für das tägliche Backup (24h-Format).",
        "label_heartbeat_enable": "Heartbeat (Uptime-Monitor) aktivieren",
        "label_heartbeat_url": "Heartbeat-URL (Optional)",
        "help_heartbeat_url": "URL für Uptime Kuma/Healthchecks.io, um 'System läuft' zu signalisieren.",
        "label_heartbeat_interval": "Heartbeat-Intervall (Minuten)",
        "help_heartbeat_interval": "Häufigkeit des Pings. Auf 0 setzen zum Deaktivieren.",
        "toggle_edit": "Entsperren / Einstellungen bearbeiten",
        "toggle_show_backup_password": "Backup-Passwort anzeigen",
        "help_show_backup_password": "Zeigt das aktuelle Backup-Passwort im Einstellungsformular an.",
        "header_logs": "Systemprotokolle",
        "btn_refresh_logs": "Logs aktualisieren",
        "btn_clear_logs": "🗑️ Logs löschen",
        "status_logs_cleared": "✅ Logs erfolgreich gelöscht.",
        "btn_save_changes": "Änderungen speichern",
        "status_settings_saved": "✅ Einstellungen gespeichert! Neu laden...",
        "error_backup_pass_required": "⛔ Das Backup-Passwort darf nicht leer sein.",
        
        # Portainer Backup
        "subheader_portainer_backup": "Portainer Konfigurationssicherung",
        "btn_backup_portainer": "📦 Nur Portainer-Konfiguration sichern",
        "status_backup_portainer_start": "Sichere Portainer-Konfiguration...",
        "status_backup_portainer_success": "✅ Portainer-Konfigurationssicherung erfolgreich!",
        "status_backup_portainer_failed": "❌ Portainer-Sicherung fehlgeschlagen!",

        # Progress Messages
        "progress_processing_group": "Verarbeite Gruppe: {group} ({count} Container)",
        "progress_stopping": "⏹️ Stoppe {group}...",
        "progress_snapshot": "📸 Schnappschuss: {path}",
        "progress_error_group": "❌ Fehler in Gruppe {group}: {error}",
        "progress_restarting": "▶️ Starte {group} neu...",
        "progress_password_error": "❌ Fehler: BACKUP_PASSWORD nicht gesetzt.",
        "progress_no_containers": "⚠️ Keine Container gefunden.",
        "progress_backup_portainer": "📦 Sichere Portainer-Konfiguration...",
        "progress_no_data": "❌ Keine Daten zum Sichern gefunden.",
        "progress_compressing": "🗜️ Komprimiere Archiv (dies kann eine Weile dauern)...",
        "progress_compression_failed": "❌ Komprimierung fehlgeschlagen: {error}",
        "progress_uploading": "☁️ Hochladen in die Cloud...",
        "progress_upload_success": "✅ Cloud-Synchronisierung erfolgreich. Lokales Archiv wird bereinigt.",
        "progress_upload_failed": "⚠️ Cloud-Synchronisierung fehlgeschlagen.",

        # Login
        "label_username": "Benutzername",
        "label_password": "Passwort",
        "btn_login": "Anmelden",
        "error_login_failed": "❌ Ungültiger Benutzername oder Passwort",
        "btn_logout": "Abmelden",
        "header_login": "🔐 Admin-Login",
        "label_web_ui_username": "Web-UI Benutzername",
        "label_web_ui_password": "Web-UI Passwort",
        "help_web_ui_creds": "Anmeldeinformationen für dieses Dashboard.",

        # Rclone Editor
        "subheader_rclone_editor": "📝 Rclone Konfigurations-Editor",
        "btn_save_rclone": "💾 Rclone-Konfiguration speichern",
        "status_rclone_saved": "✅ Rclone-Konfiguration erfolgreich gespeichert!",
        "error_rclone_save": "❌ Fehler beim Speichern: {error}",
        "warning_ro_mount": "⚠️ Warnung: Datei ist schreibgeschützt. Bitte entfernen Sie ':ro' aus docker-compose.yml",
        
        # UI Strings
        "unknown_permission_denied": "Unbekannt (Zugriff verweigert)",
        "info_rclone_not_found": "rclone.conf nicht gefunden. Sie können es hier erstellen.",
        "status_test_running": "Test...",
        "warning_portainer_required": "Portainer URL & Token erforderlich.",
        "warning_gotify_required": "Gotify URL & Token erforderlich."
    }
}

_en_trans = TRANSLATIONS["en"]

def get_text(lang_code, key):
    """Retrieves translation for the given key and language code."""
    try:
        return TRANSLATIONS[lang_code][key]
    except KeyError:
        return TRANSLATIONS.get(lang_code, _en_trans).get(key, f"[{key}]")
